<?php
use CRM_RelateEntities_ExtensionUtil as E;

return [
  'name' => 'RelateEntities',
  'table' => 'civicrm_relate_entities',
  'class' => 'CRM_RelateEntities_DAO_RelateEntities',
  'getInfo' => fn() => [
    'title' => E::ts('Relate Entities'),
    'title_plural' => E::ts('Relate Entitieses'),
    'description' => E::ts('Related entity'),
    'log' => TRUE,
    'add' => '1.0',
  ],
  'getFields' => fn() => [
    'id' => [
      'title' => E::ts('ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Number',
      'required' => TRUE,
      'description' => E::ts('Unique Related Entity ID'),
      'add' => '1.0',
      'primary_key' => TRUE,
      'auto_increment' => TRUE,
    ],
    'entity_table_a' => [
      'title' => E::ts('Entity Table A'),
      'sql_type' => 'varchar(64)',
      'input_type' => 'Text',
      'required' => TRUE,
      'description' => E::ts('May contain civicrm_financial_item, civicrm_contribution, civicrm_financial_trxn, civicrm_grant, etc'),
      'add' => '1.0',
    ],
    'entity_id_a' => [
      'title' => E::ts('Entity Id A'),
      'sql_type' => 'int unsigned',
      'input_type' => 'EntityRef',
      'required' => TRUE,
      'description' => E::ts('entry in table'),
      'add' => '1.0',
      'entity_reference' => [
        'dynamic_entity' => 'entity_table_a',
        'key' => 'id',
      ],
    ],
    'entity_table_b' => [
      'title' => E::ts('Entity Table b'),
      'sql_type' => 'varchar(64)',
      'input_type' => 'Text',
      'required' => TRUE,
      'description' => E::ts('May contain civicrm_financial_item, civicrm_contribution, civicrm_financial_trxn, civicrm_grant, etc'),
      'add' => '1.0',
    ],
    'entity_id_b' => [
      'title' => E::ts('Entity Id B'),
      'sql_type' => 'int unsigned',
      'input_type' => 'EntityRef',
      'required' => TRUE,
      'description' => E::ts('entry in table'),
      'add' => '1.0',
      'entity_reference' => [
        'dynamic_entity' => 'entity_table_b',
        'key' => 'id',
      ],
    ],
    'relationship_type_id' => [
      'title' => E::ts('Relationship Type'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Select',
      'required' => TRUE,
      'description' => E::ts('id of the relationship'),
      'add' => '1.0',
      'entity_reference' => [
        'entity' => 'RelationshipType',
        'key' => 'id',
        'on_delete' => 'CASCADE',
      ],
    ],
    'is_active' => [
      'title' => E::ts('Relationship Is Active'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'description' => E::ts('is the relationship active ?'),
      'add' => '1.1',
      'default' => TRUE,
    ],
    'created_date' => [
      'title' => E::ts('RelateEntities Created Date'),
      'sql_type' => 'timestamp',
      'input_type' => NULL,
      'description' => E::ts('When was the entry was created.'),
      'add' => '1.0',
      'default' => 'CURRENT_TIMESTAMP',
      'usage' => ['export'],
    ],
    'modified_date' => [
      'title' => E::ts('RelateEntities Modified Date'),
      'sql_type' => 'timestamp',
      'input_type' => NULL,
      'description' => E::ts('When was the entry was modified.'),
      'add' => '1.0',
      'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
      'usage' => ['export'],
    ],
  ],
];
